### ISSUE TITLE
Whether gcn5MC can be used in plant genomes

### ISSUE THREAD

**Issue by chenchen-eng** [xiaochuanle/hifimeth#1]
hello Mr Le,I'm doing research on plant genomes, and I want to ask if I can use them in plant genomes?Thanks

**Comment by aragornwubo** [comment]
It was trained on human CCS data and works on CpG motifs of different animals. I haven't tried it on plant data. In theory it should work on plant CpG motif, but not CHH or CHG motif right now.

**Comment by xiaochuanle** [comment]
We have added two examples on plant genomes to validate the applicability of hifimeth on plant genomes. See https://github.com/xiaochuanle/hifimeth/tree/master/examples-arab and https://github.com/xiaochuanle/hifimeth/tree/master/examples-oryza.

**Comment by chenchen-eng** [comment]
Thank you so much
&nbsp;


辰辰
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chuan-Le ***@***.***&gt;; 
发送时间: 2023年6月8日(星期四) 晚上9:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xiaochuanle/hifimeth] Whether gcn5MC can be used in plant genomes (Issue #1)





 
We have added two examples on plant genomes to validate the applicability of hifimeth on plant genomes. See https://github.com/xiaochuanle/hifimeth/tree/master/examples-arab and https://github.com/xiaochuanle/hifimeth/tree/master/examples-oryza.
